version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  goapp:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
