version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  goapp:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  wordpress:
    image: wordpress:5.8.2-php8.0-apache
    ports:
      - "8081:80"
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    volumes:
      - ./wordpress/index.php:/var/www/html/wp-content/themes/twentytwenty/index.php

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    command: ['--skip-name-resolve', '--skip-networking=false']
