linters-settings:
  revive:
    config:
      - name: empty-block
        severity: warning
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    shadow: true

linters:
  enable:
    - revive
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

run:
  tests: true
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
