name: Next.js CI

on: [push, pull_request]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nextjs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t chitrakshipuri/nextjs-app:latest ./nextjs
          docker tag chitrakshipuri/nextjs-app:latest chitrakshipuri/nextjs-app:$(git rev-parse --short HEAD)

      - name: Push Docker image
        run: |
          docker push chitrakshipuri/nextjs-app:latest
          docker push chitrakshipuri/nextjs-app:$(git rev-parse --short HEAD)
