name: WordPress CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t chitrakshipuri/wordpress:latest .
          docker tag chitrakshipuri/wordpress:latest chitrakshipuri/wordpress:$(git rev-parse --short HEAD)

      - name: Push Docker image
        run: |
          docker push chitrakshipuri/wordpress:latest
          docker push chitrakshipuri/wordpress:$(git rev-parse --short HEAD)
